Traceback (most recent call last):
  File "mpy_cross/SPB_2021b.py", line 7, in <module>
SyntaxError: 'continue' within finally
